### ISSUE TITLE
OL UL issue

### ISSUE THREAD

**Issue by ShKlinkenberg** [ShareStats/itembank#17]
https://github.com/ShareStats/itembank/blob/2a6f1c925507bf876eda79926930a8a76dfb4361/Measurement-Level/uva-interval-814-nl/uva-interval-814-nl.Rmd#L20

Hi @tasospsy and @screambeard could it be the ( after the * are the cause of the problem with compiling? Looking at het question the brackets are completely irrelevant. We could change the (a) to A and (b) to B.

**Comment by tasospsy** [comment]
It reads the ' (a) ' as an ordered list, also in html, so it is not an exams2grasple issue. Removing the parentheses may solve the problem. I will let you know

**Comment by tasospsy** [comment]
change in 10 items with commit f07382a582e20a4f9aaa212ad8516591195c236f
