### ISSUE TITLE
Still an error on item 1150

### ISSUE THREAD

**Issue by ShKlinkenberg** [ShareStats/itembank#19]
https://github.com/ShareStats/itembank/blob/c7830cf0b82b894a34a251fa9682ae80be04b6d1/Probability/uva-elementary-probability-1150-nl/uva-taxonomyerror--1150-nl.Rmd#L1

@tasospsy and @lindemann09 this item is stil not compiling to HTML QTI or TV. But I just don't see what is wrong. It is nearly identical to item 1149 which is not showing any problems anymore.

Could one of you have a quick look to see if you can catch what I'm missing?

**Comment by tasospsy** [comment]
The folder name does not match the Rmd name?

**Comment by ShKlinkenberg** [comment]
The file name was changed indeed. Thanks @tasospsy, I have absolutely no idea how this happened. I resolved the issue.

**Comment by ShKlinkenberg** [comment]
Corrected file name
