### ISSUE TITLE
Strange item 2

### ISSUE THREAD

**Issue by lindemann09** [ShareStats/itembank#3]
please check Descriptive-statistics/uu-Percentile-800-nl/uu-Percentile-800-nl.Rmd

https://github.com/ShareStats/itembank/tree/main/Descriptive-statistics/uu-Percentile-800-nl

**Comment by ShKlinkenberg** [comment]
Also just delete

From: Oliver Lindemann ***@***.***>
Date: Tuesday, 8 November 2022 at 11:54
To: ShareStats/itembank ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShareStats/itembank] Strange item 2 (Issue #3)

please check Descriptive-statistics/uu-Percentile-800-nl/uu-Percentile-800-nl.Rmd

**Comment by lindemann09** [comment]
Fixed da022e123bc63fbc28f3e451009050e6940bc6bb
