### ISSUE TITLE
Check duplicates

### ISSUE THREAD

**Issue by lindemann09** [ShareStats/itembank#5]
The following item are duplicates:

```
1.
   - Factor-analysis/uu-factor-analysis-030-nl/uu-factor-analysis-030-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-030-nl/uu-factor-analysis-030-nl.Rmd
2.
   - Factor-analysis/uu-Compontent correlation matrix-024-nl/uu-Compontent-correlation-matrix-024-nl.Rmd
   - Inferential_Statistics/uu-Compontent correlation matrix-024-nl/uu-Compontent-correlation-matrix-024-nl.Rmd
3.
   - Factor-analysis/uu-factor-analysis-032-nl/uu-factor-analysis-032-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-032-nl/uu-factor-analysis-032-nl.Rmd
4.
   - Factor-analysis/uu-explained variance-011-nl/uu-explained-variance-011-nl.Rmd
   - Inferential_Statistics/uu-explained variance-011-nl/uu-explained-variance-011-nl.Rmd
5.
   - Factor-analysis/uu-Scree plot-001-nl/uu-Scree-plot-001-nl.Rmd
   - Inferential_Statistics/uu-Scree plot-001-nl/uu-Scree-plot-001-nl.Rmd
6.
   - Factor-analysis/uu-Compontent correlation matrix-023-nl/uu-Compontent-correlation-matrix-023-nl.Rmd
   - Inferential_Statistics/uu-Compontent correlation matrix-023-nl/uu-Compontent-correlation-matrix-023-nl.Rmd
7.
   - Factor-analysis/uu-factor-analysis-014-nl/uu-factor-analysis-014-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-014-nl/uu-factor-analysis-014-nl.Rmd
8.
   - Factor-analysis/uu-Scree plot-007-nl/uu-Scree-plot-007-nl.Rmd
   - Inferential_Statistics/uu-Scree plot-007-nl/uu-Scree-plot-007-nl.Rmd
9.
   - Factor-analysis/uu-Exploratory factor analysis-800-nl/uu-Exploratory-factor-analysis-800-nl.Rmd
   - Inferential_Statistics/uu-Exploratory factor analysis-800-nl/uu-Exploratory-factor-analysis-800-nl.Rmd
10.
   - Factor-analysis/uu-factor-analysis-010-nl/uu-factor-analysis-010-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-010-nl/uu-factor-analysis-010-nl.Rmd
11.
   - Factor-analysis/uu-Eigenvalues-031-nl/uu-Eigenvalues-031-nl.Rmd
   - Inferential_Statistics/uu-Eigenvalues-031-nl/uu-Eigenvalues-031-nl.Rmd
12.
   - Factor-analysis/uu-Compontent correlation matrix-012-nl/uu-Compontent-correlation-matrix-012-nl.Rmd
   - Inferential_Statistics/uu-Compontent correlation matrix-012-nl/uu-Compontent-correlation-matrix-012-nl.Rmd
13.
   - Factor-analysis/uu-factor-analysis-019-nl/uu-factor-analysis-019-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-019-nl/uu-factor-analysis-019-nl.Rmd
14.
   - Factor-analysis/uu-Factor loadings-016-nl/uu-Factor-loadings-016-nl.Rmd
   - Inferential_Statistics/uu-Factor loadings-016-nl/uu-Factor-loadings-016-nl.Rmd
15.
   - Factor-analysis/uu-factor-analysis-015-nl/uu-factor-analysis-015-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-015-nl/uu-factor-analysis-015-nl.Rmd
16.
   - Factor-analysis/uu-Factor loadings-001-nl/uu-Factor-loadings-001-nl.rmd
   - Inferential_Statistics/uu-Factor loadings-001-nl/uu-Factor-loadings-001-nl.rmd
17.
   - Factor-analysis/uu-Rotations-020-nl/uu-Rotations-020-nl.Rmd
   - Inferential_Statistics/uu-Rotations-020-nl/uu-Rotations-020-nl.Rmd
18.
   - Factor-analysis/uu-factor-analysis-021-nl/uu-factor-analysis-021-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-021-nl/uu-factor-analysis-021-nl.Rmd
19.
   - Factor-analysis/uu-factor-analysis-029-nl/uu-factor-analysis-029-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-029-nl/uu-factor-analysis-029-nl.Rmd
20.
   - Factor-analysis/uu-factor-analysis-027-nl/uu-factor-analysis-027-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-027-nl/uu-factor-analysis-027-nl.Rmd
21.
   - Factor-analysis/uu-Factor loadings-004-nl/uu-Factor-loadings-004-nl.Rmd
   - Inferential_Statistics/uu-Factor loadings-004-nl/uu-Factor-loadings-004-nl.Rmd
22.
   - Factor-analysis/uu-Eigenvalues-003-nl/uu-Eigenvalues-003-nl.Rmd
   - Inferential_Statistics/uu-Eigenvalues-003-nl/uu-Eigenvalues-003-nl.Rmd
23.
   - Factor-analysis/uu-factor-analysis-017-nl/uu-factor-analysis-017-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-017-nl/uu-factor-analysis-017-nl.Rmd
24.
   - Factor-analysis/uu-factor-analysis-028-nl/uu-factor-analysis-028-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-028-nl/uu-factor-analysis-028-nl.Rmd
25.
   - Factor-analysis/uu-Explained variance-008-nl/uu-Explained-variance-008-nl.Rmd
   - Inferential_Statistics/uu-Explained variance-008-nl/uu-Explained-variance-008-nl.Rmd
26.
   - Factor-analysis/uu-compontent correlation matrix-002-nl/uu-compontent-correlation-matrix-002-nl.Rmd
   - Inferential_Statistics/uu-compontent correlation matrix-002-nl/uu-compontent-correlation-matrix-002-nl.Rmd
27.
   - Factor-analysis/uu-factor-analysis-009-nl/uu-factor-analysis-009-nl.Rmd
   - Inferential_Statistics/uu-factor-analysis-009-nl/uu-factor-analysis-009-nl.Rmd
28.
   - Factor-analysis/uu-Eigenvalues-013-nl/uu-Eigenvalues-013-nl.Rmd
   - Inferential_Statistics/uu-Eigenvalues-013-nl/uu-Eigenvalues-013-nl.Rmd
29.
   - Distributions/vufgb-normal-003-nl/vufgb-normal-003-nl.Rmd
   - Distributions/vufgb-normal-303-nl/vufgb-normal-303-nl.Rmd
30.
   - Descriptive-statistics/vufsw-z-score-0096-nl/vufsw-z-score-0096-nl.Rmd
   - Descriptive-statistics/vufsw-zscore-0096-nl/vufsw-z-score-0096-nl.Rmd
31.
   - Descriptive-statistics/vufgb-bargraph-001-nl/vufgb-bargraph-001-en.Rmd
   - Descriptive-statistics/vufgb-bargraph-001-en/vufgb-bargraph-001-en.Rmd
32.
   - Descriptive-statistics/vufsw-width-0211-nl/vufsw-width-0211-nl.Rmd
   - Inferential_Statistics/vufsw-width-0211-nl/vufsw-width-0211-nl.Rmd
33.
   - Descriptive-statistics/vufsw-zscore-0009-nl/vufsw-z-score-0009-nl.Rmd
   - Descriptive-statistics/vufsw-z-score-0009-nl/vufsw-z-score-0009-nl.Rmd
34.
   - Descriptive-statistics/vufsw-width-1121-en/vufsw-width-1121-en.Rmd
   - Inferential_Statistics/vufsw-width-1121-en/vufsw-width-1121-en.Rmd
35.
   - Descriptive-statistics/vufsw-z-score-0032-nl/vufsw-z-score-0032-nl.Rmd
   - Descriptive-statistics/vufsw-zscore-0032-nl/vufsw-z-score-0032-nl.Rmd
36.
   - Descriptive-statistics/vufsw-zscore-1176-en/vufsw-z-score-1176-en.Rmd
   - Descriptive-statistics/vufsw-z-score-1176-en/vufsw-z-score-1176-en.Rmd
37.
   - Descriptive-statistics/uu-Percentile-800-nl/.!3145!uu-Percentile-800-nl.Rmd
   - Descriptive-statistics/uu-Percentile-800-nl/.!3662!uu-Percentile-800-nl.Rmd
38.
   - Descriptive-statistics/vufsw-z-score-0007-nl/vufsw-z-score-0007-nl.Rmd
   - Descriptive-statistics/vufsw-zscore-0007-nl/vufsw-z-score-0007-nl.Rmd
39.
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!96795!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!97790!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!97260!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!98001!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!99437!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!97450!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!99577!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!99851!uu-Measures-of-Spread-800-nl.Rmd
   - Descriptive-statistics/uu-Measures-of-Spread-800-nl/.!98307!uu-Measures-of-Spread-800-nl.Rmd
40.
   - Descriptive-statistics/vufsw-standarddeviation-0049-nl/vufsw-variabletype-1091-en/vufsw-variabletype-1091-en.Rmd
   - Variable-type/vufsw-variabletype-1091-en/vufsw-variabletype-1091-en.Rmd
41.
   - Descriptive-statistics/vufsw-z-score-1097-en/vufsw-z-score-1097-en (2).Rmd
   - Descriptive-statistics/vufsw-z-score-1097-en/vufsw-z-score-1097-en.Rmd
42.
   - Descriptive-statistics/vufsw-inferentialstatistics-0131-nl/vufsw-inferentialstatistics-0131-nl.Rmd
   - Inferential_Statistics/vufsw-inferentialstatistics-0131-nl/vufsw-inferentialstatistics-0131-nl.Rmd
43.
   - Reliability/vufsw-cronbachsalpha-0026-nl/vufsw-cronbach'salpha-0026-nl.Rmd
   - Reliability/vufsw-cronbach'salpha-0026-nl/vufsw-cronbach'salpha-0026-nl.Rmd
44.
   - Reliability/vufsw-cronbachsalpha-0070-nl/vufsw-cronbach'salpha-0070-nl.Rmd
   - Reliability/vufsw-cronbach'salpha-0070-nl/vufsw-cronbach'salpha-0070-nl.Rmd
45.
   - Reliability/vufsw-cronbach'salpha-0090-nl/vufsw-cronbach'salpha-0090-nl.Rmd
   - Reliability/vufsw-cronbachsalpha-0090-nl/vufsw-cronbach'salpha-0090-nl.Rmd
46.
   - Reliability/vufsw-cronbach'salpha-1186-nl/vufsw-cronbach'salpha-1186-nl.Rmd
   - Reliability/vufsw-cronbachsalpha-1186-nl/vufsw-cronbach'salpha-1186-nl.Rmd
47.
   - Reliability/vufsw-cronbach'salpha-1122-nl/vufsw-cronbach'salpha-1122-nl.Rmd
   - Reliability/vufsw-cronbachsalpha-1122-nl/vufsw-cronbach'salpha-1122-nl.Rmd
48.
   - Reliability/vufsw-cronbachsalpha-0025-nl/vufsw-cronbach'salpha-0025-nl.Rmd
   - Reliability/vufsw-cronbach'salpha-0025-nl/vufsw-cronbach'salpha-0025-nl.Rmd
49.
   - Reliability/vufsw-cronbachsalpha-0044-nl/vufsw-cronbach'salpha-0044-nl.Rmd
   - Reliability/vufsw-cronbach'salpha-0044-nl/vufsw-cronbach'salpha-0044-nl.Rmd
50.
   - Reliability/vufsw-cronbachsalpha-1248-en/vufsw-cronbach'salpha-1248-en.Rmd
   - Reliability/vufsw-cronbach'salpha-1248-en/vufsw-cronbach'salpha-1248-en.Rmd
51.
   - Reliability/vufsw-cronbachsalpha-0051-nl/vufsw-cronbach'salpha-0051-nl.Rmd
   - Reliability/vufsw-cronbach'salpha-0051-nl/vufsw-cronbach'salpha-0051-nl.Rmd
52.
   - Probability/vufsw-expectedvalue-0118-nl/vufsw-expectedvalue-0118-nl.Rmd
   - Inferential_Statistics/vufsw-expectedvalue-0118-nl/vufsw-expectedvalue-0118-nl.Rmd
53.
   - Probability/vufsw-expectedvalue-0123-nl/vufsw-expectedvalue-0123-nl.Rmd
   - Inferential_Statistics/vufsw-expectedvalue-0123-nl/vufsw-expectedvalue-0123-nl.Rmd
54.
   - Probability/vufsw-expectedvalue-1098-en/vufsw-expectedvalue-1098-en.Rmd
   - Inferential_Statistics/vufsw-expectedvalue-1098-en/vufsw-expectedvalue-1098-en.Rmd
55.
   - Assumptions/vufsw-homogeneityofvariance-0263-nl/vufsw-homogeneityofvariance-0263-nl.Rmd
   - Inferential_Statistics/vufsw-confidenceintervals-0142-nl/vufsw-homogeneityofvariance-0263-nl/vufsw-homogeneityofvariance-0263-nl.Rmd
56.
   - Inferential_Statistics/vufsw-simplelinearregression-0219-nl/vufsw-simple_linear_regression-0219-nl.Rmd
   - Inferential_Statistics/vufsw-simple_linear_regression-0219-nl/vufsw-simple_linear_regression-0219-nl.Rmd
57.
   - Inferential_Statistics/vufsw-t-test-1006-en/vufsw-t-test-1006-en.Rmd
   - Inferential_Statistics/vufsw-ttest-1006-en/vufsw-t-test-1006-en.Rmd
58.
   - Inferential_Statistics/vufsw-simple_linear_regression-0166-nl/vufsw-simple_linear_regression-0166-nl.Rmd
   - Inferential_Statistics/vufsw-simplelinearregression-0166-nl/vufsw-simplelinearregression-0166-nl.Rmd
59.
   - Inferential_Statistics/vufsw-twoway_anova-0271-nl/vufsw-twoway_anova-0271-nl.Rmd
   - Inferential_Statistics/vufsw-twowayanova-0271-nl/vufsw-twoway_anova-0271-nl.Rmd
60.
   - Inferential_Statistics/vufgb-regression-013-nl/vufgb-regression-013-nl.Rmd
   - Inferential_Statistics/vufgb-regression-003-en/vufgb-regression-013-nl.Rmd
61.
   - Inferential_Statistics/vufsw-t-statistic-1165-en/vufsw-t-statistic-1165-en.Rmd
   - Inferential_Statistics/vufsw-tstatistic-1165-en/vufsw-t-statistic-1165-en.Rmd
  
```

**Comment by ShKlinkenberg** [comment]
Dublicates can be removed.

From: Oliver Lindemann ***@***.***>
Date: Tuesday, 8 November 2022 at 12:29
To: ShareStats/itembank ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ShareStats/itembank] Check duplicates (Issue #5)

The following item are duplicates:

1.

   - Factor-analysis/uu-factor-analysis-030-nl/uu-factor-analysis-030-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-030-nl/uu-factor-analysis-030-nl.Rmd

2.

   - Factor-analysis/uu-Scree-plot-001-nl/uu-Scree-plot-001-nl.Rmd

   - Inferential_Statistics/uu-Scree plot-001-nl/uu-Scree-plot-001-nl.Rmd

3.

   - Factor-analysis/uu-Factor-loadings-004-nl/uu-Factor-loadings-004-nl.Rmd

   - Inferential_Statistics/uu-Factor loadings-004-nl/uu-Factor-loadings-004-nl.Rmd

4.

   - Factor-analysis/uu-Compontent-correlation-matrix-024-nl/uu-Compontent-correlation-matrix-024-nl.Rmd

   - Inferential_Statistics/uu-Compontent correlation matrix-024-nl/uu-Compontent-correlation-matrix-024-nl.Rmd

5.

   - Factor-analysis/uu-factor-analysis-032-nl/uu-factor-analysis-032-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-032-nl/uu-factor-analysis-032-nl.Rmd

6.

   - Factor-analysis/uu-Exploratory-factor-analysis-800-nl/uu-Exploratory-factor-analysis-800-nl.Rmd

   - Inferential_Statistics/uu-Exploratory factor analysis-800-nl/uu-Exploratory-factor-analysis-800-nl.Rmd

7.

   - Factor-analysis/uu-factor-analysis-014-nl/uu-factor-analysis-014-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-014-nl/uu-factor-analysis-014-nl.Rmd

8.

   - Factor-analysis/uu-Factor-loadings-001-nl/uu-Factor-loadings-001-nl.rmd

   - Inferential_Statistics/uu-Factor loadings-001-nl/uu-Factor-loadings-001-nl.rmd

9.

   - Factor-analysis/uu-factor-analysis-010-nl/uu-factor-analysis-010-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-010-nl/uu-factor-analysis-010-nl.Rmd

10.

   - Factor-analysis/uu-Eigenvalues-031-nl/uu-Eigenvalues-031-nl.Rmd

   - Inferential_Statistics/uu-Eigenvalues-031-nl/uu-Eigenvalues-031-nl.Rmd

11.

   - Factor-analysis/uu-factor-analysis-019-nl/uu-factor-analysis-019-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-019-nl/uu-factor-analysis-019-nl.Rmd

12.

   - Factor-analysis/uu-Scree-plot-007-nl/uu-Scree-plot-007-nl.Rmd

   - Inferential_Statistics/uu-Scree plot-007-nl/uu-Scree-plot-007-nl.Rmd

13.

   - Factor-analysis/uu-explained-variance-011-nl/uu-explained-variance-011-nl.Rmd

   - Inferential_Statistics/uu-explained variance-011-nl/uu-explained-variance-011-nl.Rmd

14.

   - Factor-analysis/uu-factor-analysis-015-nl/uu-factor-analysis-015-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-015-nl/uu-factor-analysis-015-nl.Rmd

15.

   - Factor-analysis/uu-Rotations-020-nl/uu-Rotations-020-nl.Rmd

   - Inferential_Statistics/uu-Rotations-020-nl/uu-Rotations-020-nl.Rmd

16.

   - Factor-analysis/uu-Explained-variance-008-nl/uu-Explained-variance-008-nl.Rmd

   - Inferential_Statistics/uu-Explained variance-008-nl/uu-Explained-variance-008-nl.Rmd

17.

   - Factor-analysis/uu-factor-analysis-021-nl/uu-factor-analysis-021-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-021-nl/uu-factor-analysis-021-nl.Rmd

18.

   - Factor-analysis/uu-Compontent-correlation-matrix-012-nl/uu-Compontent-correlation-matrix-012-nl.Rmd

   - Inferential_Statistics/uu-Compontent correlation matrix-012-nl/uu-Compontent-correlation-matrix-012-nl.Rmd

19.

   - Factor-analysis/uu-factor-analysis-029-nl/uu-factor-analysis-029-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-029-nl/uu-factor-analysis-029-nl.Rmd

20.

   - Factor-analysis/uu-factor-analysis-027-nl/uu-factor-analysis-027-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-027-nl/uu-factor-analysis-027-nl.Rmd

21.

   - Factor-analysis/uu-Eigenvalues-003-nl/uu-Eigenvalues-003-nl.Rmd

   - Inferential_Statistics/uu-Eigenvalues-003-nl/uu-Eigenvalues-003-nl.Rmd

22.

   - Factor-analysis/uu-Compontent-correlation-matrix-023-nl/uu-Compontent-correlation-matrix-023-nl.Rmd

   - Inferential_Statistics/uu-Compontent correlation matrix-023-nl/uu-Compontent-correlation-matrix-023-nl.Rmd

23.

   - Factor-analysis/uu-factor-analysis-017-nl/uu-factor-analysis-017-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-017-nl/uu-factor-analysis-017-nl.Rmd

24.

   - Factor-analysis/uu-factor-analysis-028-nl/uu-factor-analysis-028-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-028-nl/uu-factor-analysis-028-nl.Rmd

25.

   - Factor-analysis/uu-compontent-correlation-matrix-002-nl/uu-compontent-correlation-matrix-002-nl.Rmd

   - Inferential_Statistics/uu-compontent correlation matrix-002-nl/uu-compontent-correlation-matrix-002-nl.Rmd

26.

   - Factor-analysis/uu-factor-analysis-009-nl/uu-factor-analysis-009-nl.Rmd

   - Inferential_Statistics/uu-factor-analysis-009-nl/uu-factor-analysis-009-nl.Rmd

27.

   - Factor-analysis/uu-Eigenvalues-013-nl/uu-Eigenvalues-013-nl.Rmd

   - Inferential_Statistics/uu-Eigenvalues-013-nl/uu-Eigenvalues-013-nl.Rmd

28.

   - Factor-analysis/uu-Factor-loadings-016-nl/uu-Factor-loadings-016-nl.Rmd

   - Inferential_Statistics/uu-Factor loadings-016-nl/uu-Factor-loadings-016-nl.Rmd

29.

   - Distributions/vufgb-normal-003-nl/vufgb-normal-003-nl.Rmd

   - Distributions/vufgb-normal-303-nl/vufgb-normal-303-nl.Rmd

30.

   - Descriptive-statistics/vufsw-z-score-0096-nl/vufsw-z-score-0096-nl.Rmd

   - Descriptive-statistics/vufsw-zscore-0096-nl/vufsw-z-score-0096-nl.Rmd

31.

   - Descriptive-statistics/vufsw-width-0211-nl/vufsw-width-0211-nl.Rmd

   - Inferential_Statistics/vufsw-width-0211-nl/vufsw-width-0211-nl.Rmd

32.

   - Descriptive-statistics/vufsw-zscore-0009-nl/vufsw-z-score-0009-nl.Rmd

   - Descriptive-statistics/vufsw-z-score-0009-nl/vufsw-z-score-0009-nl.Rmd

33.

   - Descriptive-statistics/vufsw-width-1121-en/vufsw-width-1121-en.Rmd

   - Inferential_Statistics/vufsw-width-1121-en/vufsw-width-1121-en.Rmd

34.

   - Descriptive-statistics/vufsw-z-score-0032-nl/vufsw-z-score-0032-nl.Rmd

   - Descriptive-statistics/vufsw-zscore-0032-nl/vufsw-z-score-0032-nl.Rmd

35.

   - Descriptive-statistics/vufsw-zscore-1176-en/vufsw-z-score-1176-en.Rmd

   - Descriptive-statistics/vufsw-z-score-1176-en/vufsw-z-score-1176-en.Rmd

36.

   - Descriptive-statistics/vufsw-z-score-0007-nl/vufsw-z-score-0007-nl.Rmd

   - Descriptive-statistics/vufsw-zscore-0007-nl/vufsw-z-score-0007-nl.Rmd

37.

   - Descriptive-statistics/vufsw-standarddeviation-0049-nl/vufsw-variabletype-1091-en/vufsw-variabletype-1091-en.Rmd

   - Variable-type/vufsw-variabletype-1091-en/vufsw-variabletype-1091-en.Rmd

38.

   - Descriptive-statistics/vufsw-inferentialstatistics-0131-nl/vufsw-inferentialstatistics-0131-nl.Rmd

   - Inferential_Statistics/vufsw-inferentialstatistics-0131-nl/vufsw-inferentialstatistics-0131-nl.Rmd

39.

   - Probability/vufsw-expectedvalue-0118-nl/vufsw-expectedvalue-0118-nl.Rmd

   - Inferential_Statistics/vufsw-expectedvalue-0118-nl/vufsw-expectedvalue-0118-nl.Rmd

40.

   - Probability/vufsw-expectedvalue-0123-nl/vufsw-expectedvalue-0123-nl.Rmd

   - Inferential_Statistics/vufsw-expectedvalue-0123-nl/vufsw-expectedvalue-0123-nl.Rmd

41.

   - Probability/vufsw-expectedvalue-1098-en/vufsw-expectedvalue-1098-en.Rmd

   - Inferential_Statistics/vufsw-expectedvalue-1098-en/vufsw-expectedvalue-1098-en.Rmd

42.

   - Assumptions/vufsw-homogeneityofvariance-0263-nl/vufsw-homogeneityofvariance-0263-nl.Rmd

   - Inferential_Statistics/vufsw-confidenceintervals-0142-nl/vufsw-homogeneityofvariance-0263-nl/vufsw-homogeneityofvariance-0263-nl.Rmd

43.

   - Inferential_Statistics/vufsw-simplelinearregression-0219-nl/vufsw-simple_linear_regression-0219-nl.Rmd

   - Inferential_Statistics/vufsw-simple_linear_regression-0219-nl/vufsw-simple_linear_regression-0219-nl.Rmd

44.

   - Inferential_Statistics/vufsw-t-test-1006-en/vufsw-t-test-1006-en.Rmd

   - Inferential_Statistics/vufsw-ttest-1006-en/vufsw-t-test-1006-en.Rmd

45.

   - Inferential_Statistics/vufsw-simple_linear_regression-0166-nl/vufsw-simple_linear_regression-0166-nl.Rmd

   - Inferential_Statistics/vufsw-simplelinearregression-0166-nl/vufsw-simplelinearregression-0166-nl.Rmd

46.

   - Inferential_Statistics/vufsw-twoway_anova-0271-nl/vufsw-twoway_anova-0271-nl.Rmd

   - Inferential_Statistics/vufsw-twowayanova-0271-nl/vufsw-twoway_anova-0271-nl.Rmd

47.

   - Inferential_Statistics/vufgb-regression-013-nl/vufgb-regression-013-nl.Rmd

   - Inferential_Statistics/vufgb-regression-003-en/vufgb-regression-013-nl.Rmd

48.

   - Inferential_Statistics/vufsw-t-statistic-1165-en/vufsw-t-statistic-1165-en.Rmd

   - Inferential_Statistics/vufsw-tstatistic-1165-en/vufsw-t-statistic-1165-en.Rmd

**Comment by knamesnik** [comment]
These are exactly the items that I mention in Issue "Items double placed" above.
