### ISSUE TITLE
Items double placed

### ISSUE THREAD

**Issue by knamesnik** [ShareStats/itembank#7]
There are about 28 items (all UU items) about factor analysis placed in both the folder "Factor analysis" and the folder "Inferential Statistics". They can be removed from the "Inferential Statistics" folder. 
It is concerned with the items named:
uu-component correlation matrix
uu-eigenvalues
uu-explained variance
uu-exploratory factor analysis
uu-factor loadings
uu-rotations
uu-scree plot
uu-factor analysis

**Comment by lindemann09** [comment]
16f54160ab137b7e3995bf291cc921c0fd159908
