### ISSUE TITLE
eur-inferential_statistics-217-en

### ISSUE THREAD

**Issue by knamesnik** [ShareStats/itembank#9]
In this item, one of the answers reads: "both b en c are correct". With randomized answers, this cannot be an option. Can someone change the answer to: "the main effect of A, the main effect of B, and the interaction effect A*B".

**Item: eur-inferential_statistics-217-en**

**Comment by lindemann09** [comment]
[Inferential_Statistics/eur-inferential_statistics-217-en/eur-inferential_statistics-217-en.Rmd](https://github.com/ShareStats/itembank/blob/1ec3139ecd19c226892053ba21994de553586dfc/Inferential_Statistics/eur-inferential_statistics-217-en/eur-inferential_statistics-217-en.Rmd)
